FROM elixir:1.9.2-slim AS builder

# The environment to build with
ARG MIX_ENV
# Set this to true if this release is not a Phoenix app
# If you are using an umbrella project, you can change this
# argument to the directory the Phoenix app is in so that the assets
# can be built

ENV MIX_ENV=${MIX_ENV}

# By convention, /opt is typically used for applications
WORKDIR /opt/app

# This step installs all the build tools we'll need
RUN apt-get update && \
  apt-get upgrade  && \
  apt-get install -y curl && \
  curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
  curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -y \
    inotify-tools \
    nodejs \
    yarn \
    git  \
    locales \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
  && mix local.rebar --force \
  && mix local.hex --force

# This copies our app source code into the build container
COPY . .

RUN mix do deps.get, deps.compile, compile

CMD iex -S mix phx.server
